[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/dispatcher/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 3

[environments.pr.deploy]
startCommand = "echo 'NOOP'"
healthcheckPath = ""
preDeployCommand = ""
