name: Deploy

on:
  push:
    branches: [dev, main, feat/ci-cd]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      logic-system: ${{ steps.filter.outputs.logic-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            triggers:
              - 'apps/logic-system/src/**/*.ts'
            dispatcher:
              - 'apps/dispatcher/src/**/*.ts'
            subscriptions:
              - 'apps/subscription-server/src/**/*.ts'
            consumers:
              - 'apps/consumers/src/**/*.ts'

  deploy:
    runs-on: ubuntu-latest
    needs: changes
    container: ghcr.io/railwayapp/cli:latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'dev' }}
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.base_ref }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
      - name: Deploy triggers
        if: ${{ needs.changes.outputs.triggers == 'true' }}
        # run: railway up -s logic-system -e ${{ steps.env.outputs.environment }} --ci -d
        run: echo ${{ needs.changes.outputs.triggers }}
      - name: Deploy subscriptions
        if: ${{ needs.changes.outputs.subscriptions == 'true' }}
        run: echo ${{ needs.changes.outputs.subscriptions }}
      - name: Deploy dispatcher
        if: ${{ needs.changes.outputs.dispatcher == 'true' }} || ${{ needs.changes.outputs.subscriptions == 'true' }}
        run: echo ${{ needs.changes.outputs.dispatcher }}
      - name: Deploy consumers
        if: ${{ needs.changes.outputs.consumers == 'true' }}
        run: echo ${{ needs.changes.outputs.consumers }}
